### ISSUE TITLE
mappings

### ISSUE THREAD

**Issue by kaniini** [ifupdown-ng/ifupdown-ng#1]
Debian ifupdown offers mappings, but I have no idea how they work.  Are they even worth supporting?  Do people actually use mappings?  How do they work?

**Comment by BarbarossaTM** [comment]
FWIW: Never used them, don't know them either :)

**Comment by kaniini** [comment]
I don't think anyone actually uses this crazy thing.  It is a way of having a shell script preprocess the /e/n/i file, basically.
