### ISSUE TITLE
link/iface split?

### ISSUE THREAD

**Issue by andrewshadura** [ifupdown-ng/ifupdown-ng#10]
Back in the dark ages of NoWeb ifupdown, someone voiced this idea to split the hardware links and interfaces themselves in ifupdown. Something like that is implemented by networkd, albeit in different fashion.

I don’t have very specific idea about that right now, so this is mostly a place for brainstorming, but I *think* implementing that could make more flexible handling of interfaces possible and might actually simplify the implementation.

*To be extended*

**Comment by kaniini** [comment]
@BarbarossaTM would be interesting to hear your thoughts on this

**Comment by BarbarossaTM** [comment]
Hi folks,

could you elaborate a bit further what the proposed feature/change would be? I'm not sure I get what that split would look like and what one would gain from it? Is there any document from the dark ages to read?

Best
Max

**Comment by BarbarossaTM** [comment]
Is this still something we are considering?

Having thought about it a bit I'd vote for keeping the current interface model as it seems more intuiitive, less surprising and is compatible with older ifupdown*

**Comment by kaniini** [comment]
Yeah I think we should probably keep it the way it is, since people understand the model (even if it is not ideal).  Users wanting something cleaner are probably better off looking at ifstate, in my opinion.
