### ISSUE TITLE
taking down dependent interface also takes down its parent interface

### ISSUE THREAD

**Issue by mpolanski** [ifupdown-ng/ifupdown-ng#115]
I'm using ifupdown-ng 0.10.0-r2

With the following config
```
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp

auto wg0
iface wg0
	use wireguard
	address 10.0.0.1/24
	requires eth0
```
issuing `ifdown wg0` also takes down `eth0`. I believe this shouldn't happen.

**Comment by kaniini** [comment]
I agree, it should not.  As the eth0 is explicitly brought up, it should have a refcount of 2 here.
