### ISSUE TITLE
document automatic executor selection

### ISSUE THREAD

**Issue by CosmicToast** [ifupdown-ng/ifupdown-ng#117]
Some executors are automatically selected based on the presence (or absence) of some parameters.
Please document what detections are made.

Also, it would be nice if some of them could be user-configurable in some capacity (e.g installing a new executor using #116  and having it be autoselected). If such a method already exists, please document it.

**Comment by kaniini** [comment]
it would be nice to have a config option to disable the auto selection.  the way it works is that the first part before a `-` is considered part of a namespace, and the namespace is used for the `use` statement.

so `bond-members` results in `use bond`.

**Comment by CosmicToast** [comment]
This behavior is good enough for me, just needs to be documented, then. :smile:
