### ISSUE TITLE
Further / more precise documentation needed

### ISSUE THREAD

**Issue by awilfox** [ifupdown-ng/ifupdown-ng#128]
To write effective and correct tooling around the `ifupdown-ng` system, more precise documentation about how it interprets the `interfaces` file is needed.

Some of the behaviours that are undocumented right now include:

* What happens when `netmask` isn't specified and a CIDR isn't given in an `address`?  Right now per [the source](https://github.com/ifupdown-ng/ifupdown-ng/blob/632af7b716a84128c6c3fdd8d86b775024317bb5/libifupdown/interface.c#L93-L101), it seems to just assign `/24`.  Is this a temporary workaround, a compatibility shim that should be ignored, or an intended behaviour?  That is, in an ideal state with a new deployment, should an address without a CIDR be considered an error, or should it be considered a `/24`?

* Are keys case-sensitive?  In [Debian ifupdown](https://salsa.debian.org/debian/ifupdown/-/blob/master/config.c) and [ifupdown2](https://github.com/CumulusNetworks/ifupdown2/blob/master/ifupdown2/ifupdown/networkinterfaces.py), keys appear to be case-sensitive and must be specified in all lowercase.  However, when I asked the team on IRC, I received two different answers.  This should be formally documented somewhere.

* How are duplicate keys handled?  What happens if you specify multiple `netmask`?  `point-to-point`?  `link-type`?  etc.

These are just a few of the many questions that can be easily answered and solved with adequate documentation.

I would be willing to assist in writing this documentation, if that would help.  I have experience writing this type of documentation in many formats (reStructuredText, DocBook, Markdown).

**Comment by BarbarossaTM** [comment]
Some thoughts:

- We need documentation for the netmask stuff. I'm unsure what the best way to deal with a missing netmask is right now.
- As compatibility is an important goal we should stick to the all lowercase behavior of ifupdown{,2}.
- All three should raise a warning and we should set `errornous_config` to the iface

**Comment by BarbarossaTM** [comment]
Fixed by https://github.com/ifupdown-ng/ifupdown-ng/commit/c8a05a742bcb898a42ddfaa7358c2990f01d1e14
