### ISSUE TITLE
Support output directory for build artifacts

### ISSUE THREAD

**Issue by awilfox** [ifupdown-ng/ifupdown-ng#14]
It would be nice if there could be a specific output directory for build artifacts so that it doesn't clutter the tree if you are actively developing and running frequent builds.  Right now the build artifacts pollute the repository's root.

**Comment by kaniini** [comment]
Go ahead and make a patch for this.  Seems useful.

**Comment by Neustradamus** [comment]
Dear @ifupdown-ng team,

Have you seen the @petershh PR?
- https://github.com/ifupdown-ng/ifupdown-ng/pull/215
