### ISSUE TITLE
hostname not set with dhcp in 0.11.0

### ISSUE THREAD

**Issue by ncopa** [ifupdown-ng/ifupdown-ng#148]
On alpine linux edge (aarch64):

this is the `/etc/network/interfaces`:
```
auto eth0
iface eth0 inet dhcp
hostname $(hostname)
```

This is the udhcp line:
```
28482 root      0:00 /sbin/udhcpc -b -R -p /var/run/udhcpc.eth0.pid -i eth0
```

note that the `-x hostname:$IF_DHCP_HOSTNAME` was not set.

This is the environment when `/usr/libexec/ifupdown-ng/dhcp` is called:
```sh
+ env
IF_REQUIRES=MODE=depend METHOD=none IF_USE=dhcp SHLVL=2 IF_ADDRESSES= PHASE=depend IF_HOSTNAME=$(hostname) INTERFACES_FILE=/etc/network/interfaces IFACE=eth0 IF_GATEWAYS= PWD=/root 
MODE=start
METHOD=none
IF_USE=dhcp
SHLVL=2
IF_ADDRESSES=
PHASE=post-up
IF_HOSTNAME=$(hostname)
INTERFACES_FILE=/etc/network/interfaces
IFACE=eth0
IF_GATEWAYS=
PWD=/root
```

Note that IF_HOSTNAME is set and not IF_DHCP_HOSTNAME.

I suspect that aada42795c0fd1290a28e227fed7820bed8bb03d does not work as intended.

**Comment by ncopa** [comment]
workaround is to use `/etc/network/interfaces`:
```
auto eth0
iface eth0 inet dhcp
dhcp-hostname $(hostname)
```

**Comment by kaniini** [comment]
Strange regression.  Investigating.

**Comment by kaniini** [comment]
aada427 was incomplete, the handling for automatic hostname determination needed to be adjusted
