### ISSUE TITLE
Should build system use ${LIBIFUPDOWN_LIB}?

### ISSUE THREAD

**Issue by awilfox** [ifupdown-ng/ifupdown-ng#15]
There are many references to `libifupdown.a` in the Makefile, and I am wondering why it doesn't use `${LIBIFUPDOWN_LIB}` instead.

I would be happy to make a PR to fix this.

**Comment by kaniini** [comment]
seems reasonable to me :)

**Comment by kaniini** [comment]
latest git commit will address this
