### ISSUE TITLE
What is the purpose of the `usage` member of `if_applet`?

### ISSUE THREAD

**Issue by awilfox** [ifupdown-ng/ifupdown-ng#16]
There is no place in the codebase where the `usage` member of `if_applet` is used.

Furthermore, since the `usage` methods seem to all call `exit(3)` themselves, there is no way to do a "print all usage statements" or similar.

**Comment by kaniini** [comment]
the idea is to eventually do the --help dispatch in the multicall.c itself, basically.

**Comment by awilfox** [comment]
I'm not sure if that would be a good idea just because I've seen a lot of software that "overloads" `--help` (something like `--help --stuff` to show more detail about a specific option).  Then again, this would enforce a convention so `--help` behaves consistently across all applets.

My main issue with the current system is that usage always causes the exit code to be 1, even when `--help` is properly used.  This feels wrong (and for some `PS1`s, may be user-visible).  I'm not sure if the answer is to remove the exit call, or to make usage take an exit code as a parameter.  I'm currently using the second approach in my `ifstats` implementation:

```c
void
ifstats_usage(int exit_code)
{
...
        exit(exit_code);
}

...

                case 'h':
                        ifstats_usage(EXIT_SUCCESS);
                        break;

...

        if (optind >= argc)
                ifstats_usage(EXIT_FAILURE);
```

... and the applet version is just given a function that calls `ifstats_usage` with `EXIT_FAILURE`:

```c
void
ifstats_usage_applet(void)
{
        ifstats_usage(EXIT_FAILURE);
}

struct if_applet ifstats_applet = {
        .name = "ifstats",
        .main = ifstats_main,
        .usage = ifstats_usage_applet
};
```

**Comment by kaniini** [comment]
no objection to changing it to work that way.  if you want to work on that this week, go for it.

**Comment by kaniini** [comment]
i think with my argument parsing overhaul this can be closed
