### ISSUE TITLE
source /etc/network/interfaces.d/* not supported

### ISSUE THREAD

**Issue by MPW1412** [ifupdown-ng/ifupdown-ng#202]
Hello,

ifupdown1's syntax for sourcing doesn't seem to be supported in ifupdown-ng:

```
source /etc/network/interfaces.d/*
```
This leads to an interface not found error for every interface from there and  breaks compatibility with ifupdown1.

Workaround:

```
source-directory /etc/network/interfaces.d/
```

Best,
Matthias

**Comment by kaniini** [comment]
This should be implemented in the upcoming 0.13 release branch.
