### ISSUE TITLE
GRE executor

### ISSUE THREAD

**Issue by kaniini** [ifupdown-ng/ifupdown-ng#26]
An executor for configuring GRE tunnels using iproute2.

```
auto gre0
iface gre0
   use gre
   requires eth0

   gre-endpoint 1.2.3.4
   gre-source 5.6.7.8

   gre-ttl 255
   gre-flags nopmtudisc ignore-df

   address 10.51.8.2/30
   mtu 1500
```

**Comment by BarbarossaTM** [comment]
I would like to stick to the "tunnel" mode from ifupdown1/2

See https://github.com/CumulusNetworks/ifupdown2/blob/master/ifupdown2/addons/tunnel.py#L37

**Comment by kaniini** [comment]
As discussed in IRC, the tunnel addon does not work for our customer, because we need something like `gre-flags`.  We can add a tunnel executor too.
