### ISSUE TITLE
Bring up dependent interfaces on ifup

### ISSUE THREAD

**Issue by BarbarossaTM** [ifupdown-ng/ifupdown-ng#46]
With

```
auto enp1s0
iface enp1s0
        address 192.168.20.123/24
        gateway 192.168.20.1
        vrf vrf_external

auto vrf_external
iface vrf_external
        vrf-table 1023

```

bringing up enp1s0 results in an error:

```

# ifup enp1s0
Error: argument "vrf_external" is wrong: Device does not exist

ifup: failed to change interface enp1s0 state to 'up'
```

I think ifupdown-ng should bring up dependent interfaces as well on ifup. If not by default, we need somethink like `--with-depends` / `-w`.

**Comment by kaniini** [comment]
It should bring up the vrf first.  Can you do ifquery?

**Comment by BarbarossaTM** [comment]
What do you want me to query?

**Comment by kaniini** [comment]
whole thing.  ifquery -L -P I guess :)

**Comment by kaniini** [comment]
I did some investigative work on this.  Seems the issue is actually in VRF executor -- the VRF is brought up first, but `ip set eth0 master vrf_external` no longer works for setting the VRF.

**Comment by kaniini** [comment]
Hmm, this is weird.  Actually, I can't reproduce this.  Can you provide a full `ifup -v enp1s0` log?

**Comment by kaniini** [comment]
I've done several tests, and it seems that at some point the VRF was manually deleted -- that's the only condition I can get a failure in.

We can add support for recreating it to the executor, but it seems wrong.  Maybe we should add `ifdown --zap` to notify the device manager that you took an interface down manually.
