### ISSUE TITLE
executor dependency generation

### ISSUE THREAD

**Issue by kaniini** [ifupdown-ng/ifupdown-ng#5]
In ifupdown2, it is possible for a plugin to return what interfaces would be required, with

```
def get_dependent_ifaces():
   return ['eth0', ...]
```

We can do the same with executors by adding a new `depend` phase.  This would open a pipe with the executor, and the executor would write back its dependencies.

This would only be supported for executors, not the `/etc/network/if-X.d` scripts.

**Comment by BarbarossaTM** [comment]
This would be cool! We then could stick to ifupdown1/2 namings for `bridge-ports` and `bond-slaves` etc. and thereby provide more compatibility with old configs and keep self-explanatory names.
