### ISSUE TITLE
wireguard executor

### ISSUE THREAD

**Issue by kaniini** [ifupdown-ng/ifupdown-ng#58]
Initialization of wireguard connections should be done by ifupdown-ng, instead of the service manager.  To accomplish that, we need to add a wireguard executor.

Configuration should look like:

```
iface wg0
    use wireguard
    address 1.2.3.4/24
    requires eth0  # Optionally depend on an interface that can provide a connection.
```

**Comment by mpolanski** [comment]
Looks good! I wonder if we could mimic the behavior of `wg-quick` tool and read the IP address from wireguard's configuration file. Please note that the `wg` tool does not accept the `Address` option in the `[Interface]` section. It is handled specially by `wg-quick`.

**Comment by kaniini** [comment]
Unfortunately, that's not architecturally possible.  Executors cannot dynamically change configuration like that.

**Comment by mpolanski** [comment]
Yeah, it requires parsing and rewriting the config file just like `wg-quick` script does, which is... meh.

**Comment by mpolanski** [comment]
Do we want to have an option to set custom config location in the `interfaces` file? I'm not sure what syntax could something like this have, since `use` does not accept a second argument.

**Comment by kaniini** [comment]
We can add that as `wireguard-config-path`, which would be exported as `IF_WIREGUARD_CONFIG_PATH` environment variable.

**Comment by telmich** [comment]
+1 for adding a wireguard-config-path - this is transparent and can just call out to wg-quick -- should we open a new issue to superseed #9874

**Comment by kaniini** [comment]
We already support `wireguard-config-path`, but there are no plans to ever use wg-quick, as wg-quick does things other than simply bringing up the tunnel that we would rather do ourselves.
