### ISSUE TITLE
dependent interfaces might be configured twice

### ISSUE THREAD

**Issue by BarbarossaTM** [ifupdown-ng/ifupdown-ng#63]
With the following config

```
iface enp1s0
        address xxx
        gateway yyyy
        vrf vrf_external

auto vrf_external
iface vrf_external
        vrf-table 1023
```

interface `vrf_external` will be configured twice on `ifup -a` which raises an error. The first run is done because of the dependency the second one regularly. It seems when configuring an interface based on a dependency it should be marked as configured.

**Comment by kaniini** [comment]
I think the issue here is that `ifup` itself doesn't check the configured flag (soon to be refcount) when walking the dependency graph for `auto` interfaces.

The work I am doing on refcounting will resolve this, as already configured nodes will be pruned from the graph based on `refcount > 0`.
