### ISSUE TITLE
normalize hostname property using uname(2)

### ISSUE THREAD

**Issue by kaniini** [ifupdown-ng/ifupdown-ng#74]
We have discovered that the most common use of the `hostname` property is `hostname $(hostname)`.

It would be nice to normalize the interface hostname property using uname(2) to avoid people doing weird stuff like that.

**Comment by ncopa** [comment]
I wonder if it would be an idea to use `uname(2)` if `hostname` is defined in config but is empty. eg:
```
iface eth0 dhcp
    hostname
```

**Comment by kaniini** [comment]
My idea was to set hostname if it was not explicitly set already.  I'm not sure that is a good solution though.  An empty property could also work.

**Comment by BarbarossaTM** [comment]
Are we talking about the hostname being send to a DHCP server?

**Comment by ncopa** [comment]
> Are we talking about the hostname being send to a DHCP server?
yes

> My idea was to set hostname if it was not explicitly set already. I'm not sure that is a good solution though. An empty property could also work.

I think thats a good idea. In that case specifying `hostname <empty>` or `hostname none` could mean that hostname is not passed to dhcp server.

**Comment by BarbarossaTM** [comment]
This set `hostname` to every interface which is confusing and will break #82 

I think it would be beneficial to implement support for the `method` keyword from ifupdown1 and only set hostname when `method` is `dhcp`
