### ISSUE TITLE
Check if busybox iproute needs explicit address family options for ip addr/route

### ISSUE THREAD

**Issue by BarbarossaTM** [ifupdown-ng/ifupdown-ng#97]
The `static` executor currently determines the address family of addresses and routes to configure/deconfigure.

With `iproute2` setting `-4` / `-6` isn't required. If it's not required on busybox `ìp` as well, that code part can be removed.

**Comment by kaniini** [comment]
```
localhost:/home/kaniini/ifupdown-ng# busybox ip route add 1:2:3:4::/48 dev wlan0
localhost:/home/kaniini/ifupdown-ng# busybox ip route add 1.2.3.0/24 dev wlan0
localhost:/home/kaniini/ifupdown-ng# 
```

Seems it doesn't.

**Comment by BarbarossaTM** [comment]
Can you check for addresses, too, please? If that's not required I'd go ahead and remove the `addr_family` check from the `static` executor.

**Comment by kaniini** [comment]
```
localhost:/home/kaniini/ifupdown-ng# busybox ip route add 1.2.3.4/32 dev wlan0
localhost:/home/kaniini/ifupdown-ng# busybox ip route add 1:2:3:4::/48 dev wlan0
localhost:/home/kaniini/ifupdown-ng# 
```
